# Practicing NumPy - Assignment 01

##### Name : Elvis Aptanisa - Exchange Student
##### Course : Introduction to Deep Learning

## Part A: Practicing NumPy

In [1]:
import numpy as np

##### A.1 - Resource Allocation using Matrix Multiplication

In [2]:
# Resources matrix: 3 teams × 2 months
resources = np.array([
    [120, 180],
    [90,  110],
    [160, 140]
])

# Adjustment factors: 2 months × 2 factors
adjustment = np.array([
    [1.2, 0.8],
    [0.9, 1.1]
])

# Compute final distribution
final_allocation = np.dot(resources, adjustment)

print("Final Resource Allocation (3 teams × 2 factors):")
print(final_allocation)
print()

Final Resource Allocation (3 teams × 2 factors):
[[306. 294.]
 [207. 193.]
 [318. 282.]]



##### A.2 Element-wise Operations (Production Tracking)

In [3]:
# Production of Shift A (3 factories × 7 days)
shift_a = np.array([
    [12, 15, 18, 14, 16, 13, 11],
    [22, 20, 24, 21, 19, 23, 22],
    [17, 16, 14, 18, 15, 13, 12]
])

# Production of Shift B (same shape)
shift_b = np.array([
    [8,  10, 9,  11, 7,  12, 10],
    [14, 16, 13, 15, 17, 14, 15],
    [9,  11, 10, 12, 8,  9,  11]
])

# Calculate total production (element-wise addition)
total_output = shift_a + shift_b

print("Total Production per Factory (7 days):")
print(total_output)
print()

Total Production per Factory (7 days):
[[20 25 27 25 23 25 21]
 [36 36 37 36 36 37 37]
 [26 27 24 30 23 22 23]]



##### A.3 Activation Function (Sigmoid)

In [4]:
def sigmoid_function(z):
    return 1 / (1 + np.exp(-z))

# Test values
test_values = np.array([-2.0, -0.5, 0.0, 1.5, 3.0])

# Compute sigmoid
sigmoid_output = sigmoid_function(test_values)

print("Test inputs:", test_values)
print("Sigmoid outputs:")
print(sigmoid_output)
print()

Test inputs: [-2.  -0.5  0.   1.5  3. ]
Sigmoid outputs:
[0.11920292 0.37754067 0.5        0.81757448 0.95257413]



##### # A.4 - Sigmoid Gradient (derivative)


In [5]:
def sigmoid_derivative(z):
    s = sigmoid_function(z)
    return s * (1 - s)

# Use the same test values as A.3
gradient_output = sigmoid_derivative(test_values)

print("Sigmoid Gradient for test values:")
print(gradient_output)
print()

Sigmoid Gradient for test values:
[0.10499359 0.23500371 0.25       0.14914645 0.04517666]

